backend/api/urls.py
from django.urls import path, include
from .views import (
    EventViewSet,
    PhotoViewSet,
    login,
    register,
    verify_token,
    upload_photo,
)
from rest_framework.routers import DefaultRouter


router = DefaultRouter()
router.register(r"events", EventViewSet)
router.register(r"photos", PhotoViewSet, basename='photos')

urlpatterns = [
    path("", include(router.urls)),  # Includes all API routes
    path("auth/login/", login, name="login"),
    path("auth/register/", register, name="register"),
    path("auth/verify/", verify_token, name="verify-token"),
    path("upload-photo/", upload_photo, name="upload_photo"),
]

backend/gallery/urls.py
from django.urls import path

from . import views

app_name = 'gallery'
urlpatterns = [
    path('', views.home_view, name='home'),
    path('gallery/', views.home_view, name='gallery'),
    path('gallery/<str:access_code>/', views.gallery_view, name='event_gallery'),
    path('gallery/<str:access_code>/<int:photo_id>/', views.photo_view, name='photo'),
]

backend/myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("api.urls")),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)  # For media files

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/gallery/models.py
import datetime
from django.db import models
from django.utils import timezone


class Event(models.Model):
    name = models.CharField(default='', max_length=50)
    date = models.DateField(default=datetime.date.today)
    description = models.TextField(default='')
    access_code = models.CharField(default='', max_length=6)

    def __str__(self):
        return self.name

class Upload(models.Model):
    event = models.ForeignKey(Event, on_delete=models.PROTECT)
    attendee_name = models.CharField(default='', max_length=40)
    original_file_name = models.CharField(default='', max_length=255)
    file_key = models.CharField(default='', max_length=512)
    upload_datetime = models.DateTimeField(default=timezone.now)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.original_file_name

backend/gallery/forms.py
from django import forms
from django.core.exceptions import ValidationError

class AccessCodeForm(forms.Form):
    access_code = forms.CharField(
        max_length=6,
        min_length=6,
        label='Enter Your Code',
        widget=forms.TextInput(attrs={
            'id': 'access-code-input',
            'class': 'form-control text-center text-uppercase border border-dark',
            'required': True,
            'size': 6,
            'placeholder': 'abcdef',
        })
    )

    def clean_access_code(self):
        code = self.cleaned_data['access_code']
        if not code.isalnum():
            raise ValidationError('Code must be alphanumeric.')
        return code

backend/gallery/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .forms import AccessCodeForm
from .models import Event, Upload

def home_view(request):
    form = AccessCodeForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        access_code = form.cleaned_data['access_code'].lower()
        try:
            event = Event.objects.get(access_code=access_code)
            return redirect('gallery:event_gallery', access_code=access_code)
        except Event.DoesNotExist:
            print("No such event. Redirecting...")
            form.add_error('access_code', 'No such event exists.')
    return render(request, 'gallery/home.html', {'form': form})

def gallery_view(request, access_code):
    access_code = access_code.lower()
    try:
        event = Event.objects.get(access_code=access_code)
        context = {'event': event}
        return render(request, 'gallery/gallery.html', context)
    except Event.DoesNotExist:
        form = AccessCodeForm({'access_code': access_code})
        form.add_error('access_code', 'No such event exists.')
    return render(request, 'gallery/home.html', {'form': form})

def photo_view(request, access_code, photo_id):
    upload = get_object_or_404(Upload, pk=photo_id)

    context = {
        'upload': upload,
    }

    return render(request, 'gallery/photo.html', context)

backend/gallery/templates/gallery/base.html
<!doctype html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Shared Memories{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'gallery/css/style.css' %}">
  </head>
  <body class="d-flex flex-column min-vh-100 bg-light">{% block content %}{% endblock %}</body>
</html>

backend/gallery/templates/gallery/gallery.html
{% extends "gallery/base.html" %}

{% block title %}Shared Memories{% endblock %}

{% block content %}
    <header>{% include "gallery/navbar.html" %}</header>
    <main>
      <section class="py-5 text-center container">
        <div class="row py-lg-5">
          <div class="col-lg-8 col-md-10 mx-auto">
            <h1 class="fw-light">Welcome to {{ event.name }}</h1>
            <h2 class="fw-lighter">{{ event.date }}</h2>
            <p class="lead">{{ event.description }} Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
          </div>
        </div>
      </section>
      <div class="py-1 py-md-4 py-lg-5 bg-body-tertiary">
        <div class="container">
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-3 g-2 g-md-4 g-lg-5">
          {% for upload in event.upload_set.all %}
            <div class="col">
              <div class="card shadow-sm">
                <a href="{% url 'gallery:photo' event.access_code upload.id %}">
                  {% load static %}
                  <img src="{% get_media_prefix %}events/event1/{{ upload.original_file_name }}" alt="Photo {{ upload.id }}">
                </a>
              </div>
            </div>
          {% endfor %}
            <div class="col">
              <div class="card shadow-sm">
                <svg class="sm-placeholder-img bg-dark" width="100%" height="300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect y="50" width="100%" height="200" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
              </div>
            </div>
            <div class="col">
              <div class="card shadow-sm">
                <svg class="sm-placeholder-img bg-dark" width="100%" height="300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="200" height="100%" fill="#55595c" transform="translate(-100, 0)" x="50%"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
            </div>
            </div>
            <div class="col">
              <div class="card shadow-sm">
                <svg class="sm-placeholder-img bg-dark" width="100%" height="300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect y="50" width="100%" height="200" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
              </div>
            </div>
            <div class="col">
              <div class="card shadow-sm">
                <svg class="sm-placeholder-img bg-dark" width="100%" height="300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect y="50" width="100%" height="200" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

backend/gallery/templates/gallery/home.html
{% extends "base.html" %}

{% block title %}Welcome to Shared Memories{% endblock %}

{% block content %}
  <div class="container text-center">
    <h1 class="display-4 font-weight-bold mb-4">Unlock the Memories</h1>
    <form action="{% url 'gallery:home' %}" method="POST" id="access-code-form" class="mx-auto">
      <div class="form-group">
        <label for="access-code-input" class="h5">Enter Your Code</label>
        {{ form.access_code }}
        {% for error in form.access_code.errors %}
            <div class="text-danger">{{ error }}</div>
        {% endfor %}
      </div>
      {% csrf_token %}
      <button type="submit" class="btn btn-primary btn-block mt-3">Enter</button>
    </form>
  </div>
{% endblock %}

backend/gallery/templates/gallery/navbar.html
    <nav class="navbar navbar-light bg-white shadow-sm">
      <div class="container">
        <a class="navbar-brand" href="{% url 'gallery:home' %}">Shared Memories</a>
        <ul class="nav">
          <li class="nav-item"><a class="nav-link" href="#">Upload</a>
          <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Login</a>
        </ul>
      </div>
    </nav>

backend/gallery/templates/gallery/photo.html
<!doctype html>
<html lang="en-US" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Shared Memories - {{ upload.event.name }}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'gallery/css/style.css' %}">
  </head>
  <body class="d-flex flex-column h-100 text-center bg-dark">
    <header>
      <nav class="navbar navbar-light bg-white shadow-sm" aria-labelledby="sm-primary-navigation">
        <h2 class="visually-hidden" id="sm-primary-navigation">Primary Navigation</h2>
        <div class="container">
          <ul class="nav">
            <li class="nav-item"><a class="nav-link" href="{% url 'gallery:event_gallery' upload.event.access_code %}">&lt; Back to Gallery</a>
          </ul>
        </div>
      </nav>
    </header>
    <main class="d-flex flex-grow-1 overflow-hidden justify-content-center align-items-center bg-dark">
      <div class="carousel slide h-100" id="sm-photo-viewer" data-bs-ride="carousel" data-bs-ride="carousel">
      {% for event_upload in upload.event.upload_set.all %}
        <div class="carousel-item h-100{% if event_upload.id == upload.id %} active{% endif %}">
          {% load static %}
          <img src="{% get_media_prefix %}events/event1/{{ event_upload.original_file_name }}" alt="Photo {{ event_upload.id }}">
        </div>
      {% endfor %}
        <button class="carousel-control-prev" type="button" data-bs-target="#sm-photo-viewer" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#sm-photo-viewer" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </main>
    <footer>
      <nav class="navbar navbar-light bg-white shadow-sm" aria-labelledby="sm-photo-navigation">
        <h2 class="visually-hidden" id="sm-photo-navigation">Photo Navigation</h2>
      </nav>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
  </html>